const heroImages = {
    "Season 1": [
        "s1/firstEp.jpg",
        "s1/1_.jpg",
        "s1/2_.jpg",
        "s1/3_.jpg",
        "s1/4_.jpg",
        "s1/5_.jpg",
        "s1/6_.jpg",
        "s1/7_.jpg",
        "s1/8_.jpg",
        "s1/9_.jpg",
        "s1/10_.jpg",
        "s1/11_1.jpg",
        "s1/12_.jpg",
        "s1/13_.jpg",
        "s1/14_.jpg",
        "s1/15_.jpg",
        "s1/16_.jpg",
        "s1/17_.jpg",
        "wallpapers/ToBeContinued.png",
    ],
    "Season 2": [
        "s2/2_.jpg",
        "s2/3_.jpg",
        "s2/4_.jpg",
        "s2/5_.jpg",
        "s2/6_.jpg",
        "s2/7_.jpg",
        "s2/8_.jpg",
        "s2/9_.jpg",
        "s2/10_.jpg",
        "wallpapers/ToBeContinued.png",
    ],
    "Season 3": [
        "s3/1_.jpg",
        "s3/2_.jpg",
        "s3/3_.jpg",
        "s3/4_.jpg",
        "s3/5_.jpg",
        "s3/6_.jpg",
        "s3/7_.jpg",
        "s3/8_.jpg",
        "s3/9_.jpg",
        "s3/10_.jpg",
        "s3/11_.jpg",
        "s3/12_.jpg",
        "s3/13_.jpg",
        "s3/14_.jpg",
        "s3/15_.jpg",
        "s3/16_.webp",
        "s3/17_.jpg",
        "s3/18_.jpg",
        "s3/19_.jpg",
        "s3/20_.jpg",
        "s3/21_.jpg",
        "s3/21_2.jpg",
        "s3/22_.jpg",
        "s3/23_.jpg",
        "s3/23_2.jpg",
        "s3/24_.jpg",
        "s3/25_.jpg",
        "s3/26_.jpg",
        "s3/27_.jpg",
        "s3/28_.jpg",
        "s3/29_.avif",
        "s3/30_.jpg",
        "s3/31_.jpg",
        "s3/32_.avif",
        "wallpapers/ToBeContinued.png",
    ],
    "Season 4": [
        "s4/80Ep.jpg",
        "s4/beforeRumb.jpg",
        "s4/ErenGrisha.jpg",
        "wallpapers/ToBeContinued.png",
    ],
    "The Final Season": [
        "special/E_A_Col.jpg",
        "special/Eren_Armin.jpg",
        "special/Eren_last.jpg"
    ],
    "More": [
        "wallpapers/rumbling.jpg"
    ]
}


export default heroImages